Milestone 5: Event Handlers
AndresFMoya/react-calculator pull request #5
Opened 2020-01-12 17:59 UTC by AndresFMoya

Hello TSEs!

I relate the changes made in this milestone:

**App Component Changes**
- [State Hook](https://reactjs.org/docs/hooks-state.html) was used to implement the App component as the stateful parent component. `total`, `next` and `operation` properties were initialized and default state set to null.
- `handleClick` function takes `buttonName` as an argument and replace the state based on the result of the calculate function.
- `next`, or `total`, or `0` are passed to `display` component to show the current value.
- `handleClick` function is passed to `buttonPanel` component as a `clickHandler` prop.

**buttonPannel Component Changes**
- `handleClick` function was implemented. It takes `buttonName` as an argument and returns clickHandler from props.
- `buttonPanel` component passes the `clickHandler` prop to each button in the pannel.

**button Component Changes**
- `handleClick` function was implemented. It takes `name` as an argument and returns clickHandler from props.
- `onClick` event is used to attach the `handleClick` event to the button.

Looking to hear your comments! 

Best!

Andrés F. Moya

2020-01-13 16:09 UTC, shloch requested changes
## hello @AndresFMoya 

It's all good, everything works, great job bro.

## [Required change]
I need you to fix just ONE error below, the division-by-zero error, and file for last review

Happy coding 😊😊

2020-01-13 16:09 UTC, shloch commented on src/components/Button.js
> +
why not pass the name as the function's parameter , so that it becomes a PURE FUNCTION ?

https://en.wikipedia.org/wiki/Pure_function

2020-01-13 16:09 UTC, shloch commented on src/logic/operate.js
> +    }
dont return zero, return an error on the display screen, something like "Division by 0 error" or some other creative error. Just look for a way to let user know it's an error.

2020-01-13 19:51 UTC, AndresFMoya commented
Hi @shloch. Thanks for your feedback. I just add an `error` property to show in `display` component when division by 0 occurs. Looking to hear your comments.

Best!

2020-01-14 08:16 UTC, bellom approved these changes
## Hi @AndresFMoya  :clap: 

**Great work making all the necessary corrections from the previous review.**

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit project completion form.
Goodluck in the next project :slightly_smiling_face:_ 

Best,

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-01-14 13:43 UTC, merged